##################################################################################################
# Solicitacoes service
##################################################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: relatorios
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: relatorios
    spec:
      containers:
      - name: relatorios
        image: micx0/apirelatorios:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

